### ISSUE TITLE
The requested URL was not found on the server.

### ISSUE THREAD

**Issue by vikashvsp** [Dev-Elie/User-Authentication-in-Flask#3]
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
![image](https://user-images.githubusercontent.com/79501138/176877090-89376fa3-706d-42de-b17c-ec3f9d6446d9.png)
![image](https://user-images.githubusercontent.com/79501138/176877255-d62ff72d-a14c-4f73-a763-a6cbdc1e46ae.png)

These are the issues I'm facing running this app on windows.

**Comment by OndiekOchieng** [comment]
Hi. Thank you for bringing this to my attention; indeed, I had overlooked this typo in the readme file.

Do this `set FLASK_APP=routes` not ~set FLASK_APP=main~

The file used as the application entry point is the routes.py.

Should now work for you.

Have fun coding!

**Comment by vikashvsp** [comment]
The same issues continue.....
I tried `python routes.py runserver -d` and it worked for me
